### ISSUE TITLE
ValueError after fine-tuning 

### ISSUE THREAD

**Issue by ahkarimi** [Makbari1997/VAE-KPCA-HDBSCAN#1] opened 2023-05-24 11:39 UTC
## Current Behavior
After fine-tuning the model, I encountered an error on line 80 that prevented me from saving the model's weights.
https://github.com/Makbari1997/VAE-KPCA-HDBSCAN/blob/7ce718c6a30416bc1cd06fc9c4a437dffed803ab/main.py#L80

Last commit is:
7ce718c6a30416bc1cd06fc9c4a437dffed803ab

The error message is:
```
ValueError: Layer bert weight shape (105879, 768) is not compatible with provided weight shape (30522, 768).
```

## Context (Environment)
My config is:
```
{
    "dataset" : "persian_atis",
    "seq_length" : "max",
    "finetune" : true,
    "finetune_epochs" : 60,
    "train_epochs" : 350,
    "batch_size" : 16,
    "vae_learning_rate" : 0.00002,
    "bert_freeze_layers" : 11,
    "bert" : "bert-base-multilingual-uncased",
    "activation" : "tanh",
    "vector_dim" : 768,
    "latent_dim" : 36,
    "encoder" : [512, 256, 128, 64],
    "decoder" : [64, 128, 256, 512, 768],
    "ood_threshold" : 0.2
}
```
and I am running the code on Google Colab.

**Comment by Makbari1997** [comment] 2023-05-26 18:50
Dear Amir,
Thanks for your contribution!
The problem was with default parameter of finetuning module, and the problem is solved now. Please close this issue if there is no more problems related to this issue.

**Closed as completed** 2023-05-27 08:20 UTC
